### ISSUE TITLE
✨ order 서비스와 연결

### ISSUE THREAD

**Issue by puclpu** [fcfs-commerce/product#5]
#### Description
order 서비스 통신 용 Controller 생성 및 api 구현

#### Todo
- [x] 내부 통신 용 Controller 생성 및 api 구현
  - [x] optionItem 정보 조회 api 구현
  - [x] 재고 변경 api 구현

#### ETC
